export const projects = [
  {
    id: '1',
    title: 'Current project.....',
    date: 'July 2021 - Present',
    excerpt: 'A full-stack developed application....',
    languages: 'MongoDB, Express.js, Node.js, React',
    body: 'Currently I am taking a MERN stack development course on Udemy to learn more about full-stack development. Once completed, I am going to create a dummy application, whether that will be a social media type application or an e-commerce application',
  },
  {
    id: '2',
    title: 'This website that you are reading.....',
    date: 'June 2021 - July 2021',
    excerpt: "A website that is like a 'visual resume'....",
    languages: 'Next.js, CSS, React',
    body: "Once I had completed university, after a week of relaxing, I couldn't wait to start learning again. I decided to create a website that showcased who I am and my projects and experiences. I looked at many different frameworks to use. I was tempted to stick with what I had been taught in university with HTML and PHP, but decided to challenge myself and learn something new. As it was going to be a static site, I looked at Gatsby and Next.js among others and decided to use Next.js as it seemed to be a popular choice among developers.\n\nAfter watching some tutorials and reading articles on Next.js, building the pages hasn't been as issue, but the styling and placement of containers etc, has been. Design I have discovered is a learning need that I have to improve on and gain more understanding of the CSS parameters.",
  },
  {
    id: '3',
    title: 'Mobile application for the NZ Nutrition Foundation.....',
    date: 'July 2020 - June 2021',
    excerpt: 'A cooking application aimed at 14-17 year old people....',
    languages: 'Flutter, Dart, Google Firebase',
    body: "This was for the final R&D project of the final year at university. Our brief was to put forward a project proposal for a real-life client and develop the product proposed. We had to design and build a prototype application for the NZ Nutrition Foundation so that they could build on it with future iterations until ready for release.\n\nOur team built a mobile application utilising Flutter and Dart as the language and Google Firebase to store user details, user comments and recipe information. The prototype allowed user registration, browsing for recipes and recipe submission.\n\nThe team employed distributed scrum methodology and as a group, we endured many highs and lows. One of the many lessons learned was that something that has the potential to be big as a project like this could be, a full-stack development would have been a better approach with mobile integration in a later iteration. Our structure of the Google Firebase collections meant that it was difficult to search through data and resulted in some features not to be fully functional.\n\nThe client was happy with what the team produced and it was fun using Dart. As it is an object orientated language, it was quite easy to learn. Google Firebase I found was a great package and has potential for many applications, but it wasn't suitable for us.",
  },
  {
    id: '4',
    title: 'Taxi booking website....',
    date: 'April - May 2021',
    excerpt: 'A basic website to book and assign taxis....',
    languages: 'HTML5, CSS, PHP, Javascript, SQL',
    body: "The assignment brief for this project in the second semester at year 2 at university for Web Development was to create a simple taxi booking website. It had to contain a booking page where a user could enter their details for pickup with certain fields requiring to be entered and sent a confirmation message. The admin page allowed for a search for bookings which displayed all the bookings for that search. The user was able to click on a button to assign the status of the taxi booking from 'unassigned' to 'assigned'\n\n The pages were built using HTML5 with some rudimental CSS styling, database queries with PHP and the server requests with Javascript.\n\nAnother fun project which was a great introduction into the fundamentals of web development. The hardest part for this assignment was the PHP and database queries. Missing a character in the query string proved difficult at times and problem solving it until I found an online query checker which was invaluable. This assignment recieved 90/100",
  },
  {
    id: '5',
    title: 'Virtual pet',
    date: 'May - June 2019',
    excerpt: "A 90's inspired virtual pet created from scratch....",
    languages: 'Java, Derby DB',
    body: "The assignment brief for this project in the first semester of year 2 at university for Program Design and Construction was to create anything from a list of choices and it had to contain design patterns and incorporate the use of a database to load and save data. It also had to contain unit testing.\n\nI decided to let nostalgia rule and design a virtual pet inspired by the Tamagotchi craze in the 1990's. The application utilised multi-threading to randomly reduce the pet's statistics (health, sickness, boredom, etc.,) and the statistics were saved to the DB when the user logged out and would load when they logged back in.\n\nThere were 3 different species that would randomly hatch at the start of the game so the user would not know what the pet would be. I could have used images from the internet to create this, but I wanted to not only create it all myself, but create something that looked like a child would have drawn. Hence the basic background and sprite designs. I also incorporated sounds and speech all recorded by myself. This project recieved 47/50",
  },
  {
    id: '6',
    title: 'Cinema booking system',
    date: 'September - October 2018',
    excerpt: 'A booking system to book seats at a cinema....',
    languages: 'Java',
    body: "This simple cinema booking system was the second assignment for the Programming 2 paper in semester 2 of the first year of university. Using object orientated programming with Java, the brief was to create a booking system where users could book cinema seats for a film and the booking price is displayed. \n\n Caveats for children booking were that they could only book a 'G' certificate film or had to be accompanied by an adult when booking for a 'M' certificate film. They were not allowed to book for a 'R' certificate film. The elderly ticket price was always 30% of the adult ticket price.\n\nA great fun assignment that proved to be tricky when navigating the 2D array for the seats and then assigning the event listeners. It was an interesting peek into the realm of GUI and I drew my own icons for the seats, each with different colours for the age group and empty seats. This assignment recieved full marks (50/50)",
  },
];
