export const tech = [
  {
    id: '1',
    technology: 'Dart',
    image: '/dart.png',
    link: 'https://dart.dev/',
  },
  {
    id: '2',
    technology: 'Flutter',
    image: '/flutter.png',
    link: 'https://flutter.dev',
  },
  {
    id: '3',
    technology: 'Java',
    image: '/java.jpg',
    link: 'https://www.java.com/en/',
  },
  {
    id: '4',
    technology: 'HTML/CSS',
    image: '/HTMLCSS.png',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    id: '5',
    technology: 'PHP',
    image: '/php.jpeg',
    link: 'https://www.php.net/',
  },
  {
    id: '6',
    technology: 'Python',
    image: '/python.jpg',
    link: 'https://www.python.org/',
  },
  {
    id: '7',
    technology: 'Next.JS',
    image: '/nextJS.png',
    link: 'https://nextjs.org/',
  },
  {
    id: '8',
    technology: 'tailwind',
    image: '/tailwind.png',
    link: 'https://tailwindcss.com/',
  },
  {
    id: '9',
    technology: 'React',
    image: '/React.jpeg',
    link: 'https://reactjs.org/',
  },
  {
    id: '10',
    technology: 'node.JS',
    image: '/nodejs.jpeg',
    link: 'https://nodejs.org/en/',
  },
  {
    id: '11',
    technology: 'Javascript',
    image: '/javascript.png',
    link: 'https://www.javascript.com/',
  },
  {
    id: '12',
    technology: 'Express.JS',
    image: '/express.png',
    link: 'https://expressjs.com/',
  },
  {
    id: '13',
    technology: 'GitHub',
    image: '/github.jpeg',
    link: 'https://github.com',
  },
  {
    id: '14',
    technology: 'Google Firebase',
    image: '/firebase.png',
    link: 'https://firebase.google.com/',
  },
  {
    id: '15',
    technology: 'MongoDB',
    image: '/mongoDB.png',
    link: 'https://www.mongodb.com/',
  },
  {
    id: '16',
    technology: 'Derby',
    image: '/derby.png',
    link: 'https://db.apache.org/derby/',
  },
  {
    id: '17',
    technology: 'SQL',
    image: '/sql.jpeg',
    link: 'https://www.mysql.com/',
  },
  {
    id: '18',
    technology: 'OSX/Windows/Linux',
    image: 'os.png',
    link: 'https://www.educba.com/linux-vs-mac-vs-windows/',
  },
  {
    id: '19',
    technology: 'VirtualBox',
    image: '/virtualbox.jpeg',
    link: 'https://www.virtualbox.org/',
  },
  {
    id: '20',
    technology: 'SCRUM',
    image: '/scrum.png',
    link: 'https://www.scrum.org/resources/what-is-scrum',
  },
  {
    id: '21',
    technology: 'Cloud',
    image: '/cloud.png',
    link: 'https://www.vxchnge.com/blog/different-types-of-cloud-computing',
  },
  {
    id: '22',
    technology: 'Networking',
    image: '/network.jpg',
    link: 'https://www.netacad.com/',
  },
];
