export const tech = [
  {
    id: '1',
    technology: 'Dart',
    image: '/dart.png',
    level: 'Intermediate',
  },
  {
    id: '2',
    technology: 'Flutter',
    image: '/flutter.png',
    level: 'Intermediate',
  },
  {
    id: '3',
    technology: 'Java',
    image: '/java.jpg',
    level: 'Intermediate',
  },
  {
    id: '4',
    technology: 'HTML/CSS',
    image: '/HTMLCSS.png',
    level: 'Intermediate',
  },
  {
    id: '5',
    technology: 'PHP',
    image: '/php.jpeg',
    level: 'Novice',
  },
  {
    id: '6',
    technology: 'Python',
    image: '/python.jpg',
    level: 'Novice',
  },
  {
    id: '7',
    technology: 'Next.JS',
    image: '/nextJS.png',
    level: 'Novice/Intermediate',
  },
  {
    id: '8',
    technology: 'tailwind',
    image: '/tailwind.png',
    level: 'Novice',
  },
  {
    id: '9',
    technology: 'Bootstrap',
    image: '/bootstrap.png',
    level: 'Novice',
  },
  {
    id: '10',
    technology: 'Sass',
    image: '/sass.png',
    level: 'Novice',
  },
  {
    id: '11',
    technology: 'Docker',
    image: '/docker.png',
    level: 'Novice',
  },
  {
    id: '12',
    technology: '.NET',
    image: '/net.png',
    level: 'Novice',
  },
  {
    id: '13',
    technology: 'React',
    image: '/React.jpeg',
    level: 'Novice',
  },
  {
    id: '14',
    technology: 'Redux',
    image: '/redux.png',
    level: 'Novice',
  },
  {
    id: '15',
    technology: 'node.JS',
    image: '/nodejs.jpeg',
    level: 'Novice',
  },
  {
    id: '16',
    technology: 'Javascript',
    image: '/javascript.png',
    level: 'Novice/Intermediate',
  },
  {
    id: '17',
    technology: 'Express.JS',
    image: '/express.png',
    level: 'Novice',
  },
  {
    id: '18',
    technology: 'GitHub',
    image: '/github.jpeg',
    level: 'Intermediate',
  },
  {
    id: '19',
    technology: 'Google Firebase',
    image: '/firebase.png',
    level: 'Intermediate',
  },
  {
    id: '20',
    technology: 'MongoDB',
    image: '/MongoDB.png',
    level: 'Novice',
  },
  {
    id: '21',
    technology: 'Derby',
    image: '/derby.png',
    level: 'Novice',
  },
  {
    id: '22',
    technology: 'SQL',
    image: '/sql.jpeg',
    level: 'Intermediate',
  },
  {
    id: '23',
    technology: 'OSX/Windows/Linux',
    image: 'os.png',
    level: 'Intermediate',
  },
  {
    id: '24',
    technology: 'VirtualBox',
    image: '/virtualbox.jpeg',
    level: 'Intermediate',
  },
  {
    id: '25',
    technology: 'SCRUM',
    image: '/scrum.png',
    level: 'Intermediate',
  },
  {
    id: '26',
    technology: 'Cloud',
    image: '/cloud.png',
    level: 'Novice/Intermediate',
  },
  {
    id: '27',
    technology: 'Networking',
    image: '/network.jpg',
    level: 'Novice',
  },
];
